### ISSUE TITLE
Unable to connect OBD to mac

### ISSUE THREAD

**Issue by koukumar** [brendanwhitfield/python-OBD#19]
I am trying to connect my mac to ODB which is connected to "Maruti Swift VDI".

```python
import obd
obd.debug.console = True
import obd
connection = obd.OBD("/dev/tty.OBDII-SPP")
cmd = obd.commands.RPM
response = connection.query(cmd)
print(response.value)
print(response.unit)
```

```
[obd] ========================== python-OBD (v0.4.0) ==========================
[obd] Explicit port defined
[obd] Opening serial port '/dev/tty.OBDII-SPP'
[obd] Serial port successfully opened on /dev/tty.OBDII-SPP
[obd] write: 'ATZ\r\n'
[obd] wait: 1 seconds
[obd] __read() found nothing
[obd] __read() found nothing
[obd] __read() never recieved prompt character
[obd] read: ''
[obd] write: 'ATE0\r\n'
[obd] __read() found nothing
[obd] __read() found nothing
[obd] __read() never recieved prompt character
[obd] read: ''
[obd] Connection Error:
[obd]     ATE0 did not return 'OK'
[obd] Failed to connect
[obd] =========================================================================
[obd] '010C: Engine RPM' is not supported
None
None
```

But i was able to successfully connect it via Torque mobile app. The protocol that Torque app used was "iso14230-4 KWP fast". Can you please let me know if this is supported?

**Comment by brendanwhitfield** [comment]
Try instantiating the connection with the baudrate 10400

```python
connection = obd.OBD("/dev/tty.OBDII-SPP", baudrate=10400)
```

**Comment by koukumar** [comment]
Thanks for the suggestion. Even that didn't work. Wondering would there be any problem with mac SPP?

**Comment by brendanwhitfield** [comment]
Sounds like it, python-OBD isn't getting *any* data from the device, so it's probably a setup issue. I've never used the mac bluetooth settings, but I believe you just need a simple RS-232 device.

**Comment by koukumar** [comment]
Sure. Let me try using a different device and will update. Thanks for the reply.

**Comment by brendanwhitfield** [comment]
any luck?

**Comment by koukumar** [comment]
From mac it is still not working. I moved on to Linux based machines.

**Comment by brendanwhitfield** [comment]
ok to close?

**Comment by koukumar** [comment]
Yeah sure

**Comment by koukumar** [comment]
Thanks for the help and follow up :)
